name: Build image docker, and deploy PHP app to Azure Web App with Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'test-webb'  
  DOCKER_IMAGE: 'majdaid/projet-php' 
  PHP_VERSION: '8.x' 

permissions:
  contents: read

jobs:
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                              
          file: ./Dockerfile                       
          push: true                               
          tags: ${{ env.DOCKER_IMAGE }}:1.0.${{ github.run_number }}

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: docker-build-push  
    environment:
      name: 'Development'

    steps:
      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_IMAGE }}:1.0.${{ github.run_number }}
